pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    application/javascript                js mjs;
    application/json                      json;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    image/png                             png;
    image/svg+xml                         svg svgz;
    image/x-icon                          ico;
    image/webp                            webp;
    font/woff2                            woff2;
    font/woff                             woff;
    font/ttf                              ttf;
    application/vnd.ms-fontobject         eot;
  }

  default_type  application/octet-stream;
  sendfile      on;
  gzip          on;
  gzip_types    text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

  access_log  /dev/stdout;
  error_log   /dev/stderr;

  server {
    listen $PORT;
    root /app/dist;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|mjs|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp)$ {
      expires 1y;
      add_header Cache-Control "public, immutable";
    }
  }
}
