/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as EmployeesUserIdRouteImport } from './routes/employees.$userId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const EmployeesUserIdRoute = EmployeesUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => EmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/my-tasks': typeof MyTasksRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/employees/$userId': typeof EmployeesUserIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/my-tasks': typeof MyTasksRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/employees/$userId': typeof EmployeesUserIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/my-tasks': typeof MyTasksRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/employees/$userId': typeof EmployeesUserIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/employees'
    | '/my-tasks'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/tasks'
    | '/employees/$userId'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/employees'
    | '/my-tasks'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/tasks'
    | '/employees/$userId'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/employees'
    | '/my-tasks'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/tasks'
    | '/employees/$userId'
    | '/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
  MyTasksRoute: typeof MyTasksRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/employees/$userId': {
      id: '/employees/$userId'
      path: '/$userId'
      fullPath: '/employees/$userId'
      preLoaderRoute: typeof EmployeesUserIdRouteImport
      parentRoute: typeof EmployeesRoute
    }
  }
}

interface EmployeesRouteChildren {
  EmployeesUserIdRoute: typeof EmployeesUserIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesUserIdRoute: EmployeesUserIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
  MyTasksRoute: MyTasksRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
